### ISSUE TITLE
Using Angular v1.4.7, no data visible in drop downs

### ISSUE THREAD

**Issue by jdavis57** [john-oc/acute-select#48] opened 2015-10-28 17:28 UTC
When using this with Angular v1.4.7 I get the following error:

Error: [filter:notarray] Expected array but received: 0
http://errors.angularjs.org/1.4.7/filter/notarray?p0=0
    at http://localhost:49751/lib/angular.js:68:12
    at http://localhost:49751/lib/angular.js:18391:31
    at fn (eval at <anonymous> (http://localhost:49751/lib/angular.js:13322:15), <anonymous>:4:254)
    at trackByIdExpFn (http://localhost:49751/lib/angular.js:27340:20)
    at ngRepeatAction (http://localhost:49751/lib/angular.js:27397:25)
    at Object.$watchCollectionAction [as fn] (http://localhost:49751/lib/angular.js:15691:13)
    at Scope.$digest (http://localhost:49751/lib/angular.js:15826:29)
    at Scope.$apply (http://localhost:49751/lib/angular.js:16097:24)
    at done (http://localhost:49751/lib/angular.js:10546:47)
    at completeRequest (http://localhost:49751/lib/angular.js:10744:7)

Using your sample project as is, I did not get the error. The project I am working uses the most recent version of Angular. When I changed the sample project's "~/test-pages/TestAcuteSelect.htm" line 13 from 
    `<script type="text/javascript" src="../lib/angular.1.2.26.js"></script>`
to 
    `<script type="text/javascript" src="../lib/angular.js"></script>`
where angular.js is the most recent version (v1.4.7), I receive the error in the sample project. Once this error has occurred the drop downs do not have any data visible in the drop downs. If you start typing a state name, such as Alabama in a select box with combo mode as true, you can see that it limits the search results and appears as if data is there, just with no visible text.

Any help would be greatly appreciated as this control is perfect for what I'm trying to do. Thanks!

**Comment by john-oc** [comment] 2015-11-02 23:09
On 28/10/2015 17:28, jdavis57 wrote:
>
> When using this with Angular v1.4.7 I get the following error:
>
> Error: [filter:notarray] Expected array but received: 0
> http://errors.angularjs.org/1.4.7/filter/notarray?p0=0
> at http://localhost:49751/lib/angular.js:68:12
> at http://localhost:49751/lib/angular.js:18391:31
> at fn (eval at (http://localhost:49751/lib/angular.js:13322:15), :4:254)
> at trackByIdExpFn (http://localhost:49751/lib/angular.js:27340:20)
> at ngRepeatAction (http://localhost:49751/lib/angular.js:27397:25)
> at Object.$watchCollectionAction as fn 
> <http://localhost:49751/lib/angular.js:15691:13>
> at Scope.$digest (http://localhost:49751/lib/angular.js:15826:29)
> at Scope.$apply (http://localhost:49751/lib/angular.js:16097:24)
> at done (http://localhost:49751/lib/angular.js:10546:47)
> at completeRequest (http://localhost:49751/lib/angular.js:10744:7)
>
> Using your sample project as is, I did not get the error. The project 
> I am working uses the most recent version of Angular. When I changed 
> the sample project's "~/test-pages/TestAcuteSelect.htm" line 13 from
>
> to
>
> where angular.js is the most recent version (v1.4.7), I receive the 
> error in the sample project. Once this error has occurred the drop 
> downs do not have any data present.
>
> Any help would be greatly appreciated as this control is perfect for 
> what I'm trying to do. Thanks!
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/john-oc/acute-select/issues/48>.
>
Hi,

Sorry for the slow response on this one. Will try to take a look at it 
tomorrow.

John

**Comment by gsabboz** [comment] 2015-11-07 16:41
Did you find a solution for this ?

**Comment by john-oc** [comment] 2015-11-08 20:39
Yes, the problem is in the template, where I've left in an obsolete filter. The fix is simply to remove it, i.e. replace 
> <li id="{{item.id}}" ng-repeat="item in items track by $index | filter: search" title="{{item.text}}"

with

> <li id="{{item.id}}" ng-repeat="item in items track by $index" title="{{item.text}}"

I'll get a fix committed shortly. Just having a bit of trouble with my local git repository at the moment.

**Comment by gsabboz** [comment] 2015-11-10 15:11
Thanks for your response i got it working now.

**Closed** 2015-11-10 19:02 UTC
